name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - if: startsWith(github.event.issue.title, 'Blah') == 'true'
      name: close it with comment
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          You said: ${{ github.event.issue.body }}
          And the title is ${{ github.event.issue.title }}

